package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class AutomataTransitionRule implements java.io.Serializable {
  public abstract <R,A> R accept(AutomataTransitionRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.AutomataTransition p, A arg);
    public R visit(grammar.Absyn.AutomataEmptyTransition p, A arg);

  }

}
