package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class AutomataInitRule implements java.io.Serializable {
  public abstract <R,A> R accept(AutomataInitRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.AutomataInitialState p, A arg);

  }

}
