package grammar.Absyn; // Java Package generated by the BNF Converter.

public class Generator extends GeneratorRule {
  public final IndexSequenceRule indexsequencerule_;
  public Generator(IndexSequenceRule p1) { indexsequencerule_ = p1; }

  public <R,A> R accept(grammar.Absyn.GeneratorRule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.Generator) {
      grammar.Absyn.Generator x = (grammar.Absyn.Generator)o;
      return this.indexsequencerule_.equals(x.indexsequencerule_);
    }
    return false;
  }

  public int hashCode() {
    return this.indexsequencerule_.hashCode();
  }


}
