package grammar.Absyn; // Java Package generated by the BNF Converter.

public class IndexSequence extends IndexSequenceRule {
  public final ListNumberSpaceRule listnumberspacerule_;
  public IndexSequence(ListNumberSpaceRule p1) { listnumberspacerule_ = p1; }

  public <R,A> R accept(grammar.Absyn.IndexSequenceRule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.IndexSequence) {
      grammar.Absyn.IndexSequence x = (grammar.Absyn.IndexSequence)o;
      return this.listnumberspacerule_.equals(x.listnumberspacerule_);
    }
    return false;
  }

  public int hashCode() {
    return this.listnumberspacerule_.hashCode();
  }


}
