package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class IndexSequenceRule implements java.io.Serializable {
  public abstract <R,A> R accept(IndexSequenceRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.IndexSequence p, A arg);

  }

}
