package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class NumberSpaceRule implements java.io.Serializable {
  public abstract <R,A> R accept(NumberSpaceRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.NumberSpace p, A arg);

  }

}
