package grammar.Absyn; // Java Package generated by the BNF Converter.

public class SymmetryInstance extends SymInstance {
  public final Integer integer_;
  public final ListGeneratorRule listgeneratorrule_;
  public SymmetryInstance(Integer p1, ListGeneratorRule p2) { integer_ = p1; listgeneratorrule_ = p2; }

  public <R,A> R accept(grammar.Absyn.SymInstance.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.SymmetryInstance) {
      grammar.Absyn.SymmetryInstance x = (grammar.Absyn.SymmetryInstance)o;
      return this.integer_.equals(x.integer_) && this.listgeneratorrule_.equals(x.listgeneratorrule_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.integer_.hashCode())+this.listgeneratorrule_.hashCode();
  }


}
