package grammar.Absyn; // Java Package generated by the BNF Converter.

public class SymmetryPairs extends Statement {
  public final ListSymmetryPairRule listsymmetrypairrule_;
  public SymmetryPairs(ListSymmetryPairRule p1) { listsymmetrypairrule_ = p1; }

  public <R,A> R accept(grammar.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.SymmetryPairs) {
      grammar.Absyn.SymmetryPairs x = (grammar.Absyn.SymmetryPairs)o;
      return this.listsymmetrypairrule_.equals(x.listsymmetrypairrule_);
    }
    return false;
  }

  public int hashCode() {
    return this.listsymmetrypairrule_.hashCode();
  }


}
