package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class SymmetryPairRule implements java.io.Serializable {
  public abstract <R,A> R accept(SymmetryPairRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.SymmetryPair p, A arg);

  }

}
