#!/bin/sh

if [ $(uname) = "Linux" ]; then
    pathCmd="readlink -f"
elif [ $(uname) = "Darwin" ]; then
    pathCmd="stat -f %N"
else
    pathCmd="realpath"
fi

BASEDIR=${BASEDIR:-`dirname $($pathCmd $0)`}
CPOPTS="-cp $BASEDIR/dist/livenessprover.jar:$BASEDIR/../Common/lib/commons-io-2.4.jar:$BASEDIR/../Common/lib/commons-cli-1.2.jar:$BASEDIR/../Common/lib/org.sat4j.core.jar:$BASEDIR/../Common/lib/log4j-core-2.5.jar:$BASEDIR/../Common/lib/log4j-api-2.5.jar:$BASEDIR/../Common/lib/java-cup-11a.jar"

exec java -Xss20000k -Xmx2000m -ea $CPOPTS main.Main "$@"
