#!/bin/sh

# BASEDIR=`dirname $(readlink -e $0)`
TMP=$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)/$(basename -- "$0")")
BASEDIR=$(dirname ${TMP})
OUTPUT_DIR="${BASEDIR}/output"

mkdir -p ${OUTPUT_DIR}
(cd ${OUTPUT_DIR} && ./clean_dir)

exec java -Xss20000k -Xmx2000m -ea -cp $BASEDIR/dist/livenessprover.jar:$BASEDIR/../Common/lib/commons-io-2.4.jar:$BASEDIR/../Common/lib/commons-cli-1.2.jar:$BASEDIR/../Common/lib/org.sat4j.core.jar:$BASEDIR/../Common/lib/log4j-core-2.5.jar:$BASEDIR/../Common/lib/log4j-api-2.5.jar:$BASEDIR/../Common/lib/java-cup-11a.jar main.Main "$@" | tee "${OUTPUT_DIR}/output.log"
