#!/bin/sh

exec java -Xss20000k -Xmx6000m -ea -cp dist/livenessprover.jar:lib/commons-io-2.4.jar:lib/commons-cli-1.2.jar:lib/org.sat4j.core.jar:lib/log4j-core-2.1.jar:lib/log4j-api-2.1.jar:lib/java-cup-11a.jar main.Main "$@"
