#!/bin/sh

# Check the number of command-line arguments
if [ \( "$#" -eq 0 \) ] ; then
	echo "usage: ${0} <file> [params]"
	exit 1
fi

. ./run
# exec java -Xss20000k -Xmx2000m -ea -cp $BASEDIR/dist/livenessprover.jar:$BASEDIR/../Common/lib/commons-io-2.4.jar:$BASEDIR/../Common/lib/commons-cli-1.2.jar:$BASEDIR/../Common/lib/org.sat4j.core.jar:$BASEDIR/../Common/lib/log4j-core-2.1.jar:$BASEDIR/../Common/lib/log4j-api-2.1.jar:$BASEDIR/../Common/lib/java-cup-11a.jar main.Main "$@" | tee "${OUTPUT_DIR}/output.log"

cd ${OUTPUT_DIR} && ./alltosvg
