#!/bin/sh

# Check the number of command-line arguments
if [ \( "$#" -eq 0 \) ] ; then
	echo "usage: ${0} <file> [params]"
	exit 1
fi

SRC="${1}"

# run the main script
. ./run 

cp ${SRC} "${OUTPUT_DIR}/source.txt"
cd ${OUTPUT_DIR} && ./alltosvg
