// This JLex file was machine-generated by the BNF converter
package grammar;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  public int line_num() { return (yyline+1); }
  public String buff() { return new String(yy_buffer,yy_buffer_index,10).trim(); }
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		44,
		48,
		48,
		48,
		48,
		48
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NOT_ACCEPT,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NOT_ACCEPT,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NOT_ACCEPT,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NOT_ACCEPT,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NOT_ACCEPT,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NOT_ACCEPT,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NO_ANCHOR,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NO_ANCHOR,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NO_ANCHOR,
		/* 85 */ YY_NO_ANCHOR,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NO_ANCHOR,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NO_ANCHOR,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NO_ANCHOR,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NO_ANCHOR,
		/* 100 */ YY_NO_ANCHOR,
		/* 101 */ YY_NO_ANCHOR,
		/* 102 */ YY_NO_ANCHOR,
		/* 103 */ YY_NO_ANCHOR,
		/* 104 */ YY_NO_ANCHOR,
		/* 105 */ YY_NO_ANCHOR,
		/* 106 */ YY_NO_ANCHOR,
		/* 107 */ YY_NO_ANCHOR,
		/* 108 */ YY_NO_ANCHOR,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NO_ANCHOR,
		/* 111 */ YY_NO_ANCHOR,
		/* 112 */ YY_NO_ANCHOR,
		/* 113 */ YY_NO_ANCHOR,
		/* 114 */ YY_NO_ANCHOR,
		/* 115 */ YY_NO_ANCHOR,
		/* 116 */ YY_NO_ANCHOR,
		/* 117 */ YY_NO_ANCHOR,
		/* 118 */ YY_NO_ANCHOR,
		/* 119 */ YY_NO_ANCHOR,
		/* 120 */ YY_NO_ANCHOR,
		/* 121 */ YY_NO_ANCHOR,
		/* 122 */ YY_NO_ANCHOR,
		/* 123 */ YY_NO_ANCHOR,
		/* 124 */ YY_NO_ANCHOR,
		/* 125 */ YY_NO_ANCHOR,
		/* 126 */ YY_NO_ANCHOR,
		/* 127 */ YY_NO_ANCHOR,
		/* 128 */ YY_NO_ANCHOR,
		/* 129 */ YY_NO_ANCHOR,
		/* 130 */ YY_NO_ANCHOR,
		/* 131 */ YY_NO_ANCHOR,
		/* 132 */ YY_NO_ANCHOR,
		/* 133 */ YY_NO_ANCHOR,
		/* 134 */ YY_NO_ANCHOR,
		/* 135 */ YY_NO_ANCHOR,
		/* 136 */ YY_NO_ANCHOR,
		/* 137 */ YY_NO_ANCHOR,
		/* 138 */ YY_NO_ANCHOR,
		/* 139 */ YY_NO_ANCHOR,
		/* 140 */ YY_NO_ANCHOR,
		/* 141 */ YY_NO_ANCHOR,
		/* 142 */ YY_NO_ANCHOR,
		/* 143 */ YY_NO_ANCHOR,
		/* 144 */ YY_NO_ANCHOR,
		/* 145 */ YY_NO_ANCHOR,
		/* 146 */ YY_NO_ANCHOR,
		/* 147 */ YY_NO_ANCHOR,
		/* 148 */ YY_NO_ANCHOR,
		/* 149 */ YY_NO_ANCHOR,
		/* 150 */ YY_NO_ANCHOR,
		/* 151 */ YY_NO_ANCHOR,
		/* 152 */ YY_NO_ANCHOR,
		/* 153 */ YY_NO_ANCHOR,
		/* 154 */ YY_NO_ANCHOR,
		/* 155 */ YY_NO_ANCHOR,
		/* 156 */ YY_NO_ANCHOR,
		/* 157 */ YY_NO_ANCHOR,
		/* 158 */ YY_NO_ANCHOR,
		/* 159 */ YY_NO_ANCHOR,
		/* 160 */ YY_NO_ANCHOR,
		/* 161 */ YY_NO_ANCHOR,
		/* 162 */ YY_NO_ANCHOR,
		/* 163 */ YY_NO_ANCHOR,
		/* 164 */ YY_NO_ANCHOR,
		/* 165 */ YY_NO_ANCHOR,
		/* 166 */ YY_NO_ANCHOR,
		/* 167 */ YY_NO_ANCHOR,
		/* 168 */ YY_NO_ANCHOR,
		/* 169 */ YY_NO_ANCHOR,
		/* 170 */ YY_NO_ANCHOR,
		/* 171 */ YY_NO_ANCHOR,
		/* 172 */ YY_NO_ANCHOR,
		/* 173 */ YY_NO_ANCHOR,
		/* 174 */ YY_NO_ANCHOR,
		/* 175 */ YY_NO_ANCHOR,
		/* 176 */ YY_NO_ANCHOR,
		/* 177 */ YY_NO_ANCHOR,
		/* 178 */ YY_NO_ANCHOR,
		/* 179 */ YY_NO_ANCHOR,
		/* 180 */ YY_NO_ANCHOR,
		/* 181 */ YY_NO_ANCHOR,
		/* 182 */ YY_NO_ANCHOR,
		/* 183 */ YY_NO_ANCHOR,
		/* 184 */ YY_NO_ANCHOR,
		/* 185 */ YY_NO_ANCHOR,
		/* 186 */ YY_NO_ANCHOR,
		/* 187 */ YY_NO_ANCHOR,
		/* 188 */ YY_NO_ANCHOR,
		/* 189 */ YY_NO_ANCHOR,
		/* 190 */ YY_NO_ANCHOR,
		/* 191 */ YY_NO_ANCHOR,
		/* 192 */ YY_NO_ANCHOR,
		/* 193 */ YY_NO_ANCHOR,
		/* 194 */ YY_NO_ANCHOR,
		/* 195 */ YY_NO_ANCHOR,
		/* 196 */ YY_NO_ANCHOR,
		/* 197 */ YY_NO_ANCHOR,
		/* 198 */ YY_NO_ANCHOR,
		/* 199 */ YY_NO_ANCHOR,
		/* 200 */ YY_NO_ANCHOR,
		/* 201 */ YY_NO_ANCHOR,
		/* 202 */ YY_NO_ANCHOR,
		/* 203 */ YY_NO_ANCHOR,
		/* 204 */ YY_NO_ANCHOR,
		/* 205 */ YY_NO_ANCHOR,
		/* 206 */ YY_NO_ANCHOR,
		/* 207 */ YY_NO_ANCHOR,
		/* 208 */ YY_NO_ANCHOR,
		/* 209 */ YY_NO_ANCHOR,
		/* 210 */ YY_NO_ANCHOR,
		/* 211 */ YY_NO_ANCHOR,
		/* 212 */ YY_NO_ANCHOR,
		/* 213 */ YY_NO_ANCHOR,
		/* 214 */ YY_NO_ANCHOR,
		/* 215 */ YY_NO_ANCHOR,
		/* 216 */ YY_NO_ANCHOR,
		/* 217 */ YY_NO_ANCHOR,
		/* 218 */ YY_NO_ANCHOR,
		/* 219 */ YY_NO_ANCHOR,
		/* 220 */ YY_NO_ANCHOR,
		/* 221 */ YY_NO_ANCHOR,
		/* 222 */ YY_NO_ANCHOR,
		/* 223 */ YY_NO_ANCHOR,
		/* 224 */ YY_NO_ANCHOR,
		/* 225 */ YY_NO_ANCHOR,
		/* 226 */ YY_NO_ANCHOR,
		/* 227 */ YY_NO_ANCHOR,
		/* 228 */ YY_NO_ANCHOR,
		/* 229 */ YY_NO_ANCHOR,
		/* 230 */ YY_NO_ANCHOR,
		/* 231 */ YY_NO_ANCHOR,
		/* 232 */ YY_NO_ANCHOR,
		/* 233 */ YY_NO_ANCHOR,
		/* 234 */ YY_NO_ANCHOR,
		/* 235 */ YY_NO_ANCHOR,
		/* 236 */ YY_NO_ANCHOR,
		/* 237 */ YY_NO_ANCHOR,
		/* 238 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"48:9,52,46,48,52,45,48:18,52,48:6,51,48:2,47,48,9,5,8,7,12,14,15,49:7,3,4,4" +
"8:2,6,48:2,40,50,36,50:2,10,28,50,11,50:2,39,50:3,13,50,44,27,34,32,50,41,5" +
"0:3,48:4,51,48,16,50,17,31,18,50,23,37,21,50,38,30,26,22,25,19,50,33,29,20," +
"24,42,50,35,43,50,1,48,2,48:66,50:23,48,50:31,48,50:8,48:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,239,
"0,1:5,2,1,3,4,5,1:2,6,1,3:3,1:2,7,3:12,1:4,8,9,10,11,12,13,14,15,16,17,18,1" +
"9,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,4" +
"4,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,6" +
"9,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,9" +
"4,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,11" +
"4,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,1" +
"33,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151," +
"152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170" +
",171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,18" +
"9,190,191,192,193,194,195,196,197,198,199,200,3,201,202,203,204,205,206,207" +
",208")[0];

	private int yy_nxt[][] = unpackFromString(209,53,
"1,2,3,4,5,37,-1,6,40,7,8,9,10,38,10:2,41,209,228,230,231,72,232,230,233,230" +
",234,230:2,235,73,230:2,118,230:11,11:2,-1:2,10,230,-1,11,-1:60,42,-1:39,13" +
",-1:15,230:35,-1:4,230:3,-1:11,230:2,15,230:32,-1:4,230:3,-1:13,10,-1,10:2," +
"-1:33,10,-1:50,19,-1:15,230:30,142,230:4,-1:4,230:3,-1:7,12,-1:56,230:4,16," +
"17,230:29,-1:4,230:3,-1:8,35,-1:39,46,-1:13,14,-1:54,230:7,119,230:6,120,23" +
"0:20,-1:4,230:3,-1:2,42:45,18,42:6,-1:10,230:10,20,230:24,-1:4,230:3,-1,1,3" +
"3:44,-1,34,39,33:5,-1:10,230:9,21,230:25,-1:4,230:3,-1:8,36,-1:55,230:12,22" +
",230:22,-1:4,230:3,-1,1,-1:62,230:13,23,230:21,-1:4,230:3,-1:11,230:19,24,2" +
"30:15,-1:4,230:3,-1:11,230:19,25,230:15,-1:4,230:3,-1:11,230:19,26,230:15,-" +
"1:4,230:3,-1:11,230:13,27,230:21,-1:4,230:3,-1:11,230:19,28,230:15,-1:4,230" +
":3,-1:11,230:10,29,230:24,-1:4,230:3,-1:11,230:13,30,230:21,-1:4,230:3,-1:1" +
"1,230:27,31,230:7,-1:4,230:3,-1:11,230:13,32,230:21,-1:4,230:3,-1:11,230:11" +
",43,230:23,-1:4,230:3,-1:11,230:15,45,230:19,-1:4,230:3,-1:11,230:15,47,230" +
":19,-1:4,230:3,-1:11,230:12,49,230:22,-1:4,230:3,-1:11,230:8,50,230:26,-1:4" +
",230:3,-1:11,230:19,51,230:15,-1:4,230:3,-1:11,230:12,52,230:22,-1:4,230:3," +
"-1:11,230:12,53,230:22,-1:4,230:3,-1:11,230:12,54,230:22,-1:4,230:3,-1:11,2" +
"30:12,55,230:22,-1:4,230:3,-1:11,230:12,56,230:22,-1:4,230:3,-1:11,230:10,5" +
"7,230:24,-1:4,230:3,-1:11,230:12,58,230:22,-1:4,230:3,-1:11,230:12,59,230:2" +
"2,-1:4,230:3,-1:11,230:15,60,230:19,-1:4,230:3,-1:11,230:11,61,230:23,-1:4," +
"230:3,-1:11,230:11,62,230:23,-1:4,230:3,-1:11,230:11,63,230:23,-1:4,230:3,-" +
"1:11,230:8,64,230:26,-1:4,230:3,-1:11,230:15,65,230:19,-1:4,230:3,-1:11,230" +
":11,66,230:23,-1:4,230:3,-1:11,230:15,67,230:19,-1:4,230:3,-1:11,230:6,68,2" +
"30:28,-1:4,230:3,-1:11,230:11,69,230:23,-1:4,230:3,-1:11,230:13,70,230:21,-" +
"1:4,230:3,-1:11,230:11,71,230:23,-1:4,230:3,-1:11,230:10,74,230:24,-1:4,230" +
":3,-1:11,230:10,75,230:24,-1:4,230:3,-1:11,230:23,76,230:11,-1:4,230:3,-1:1" +
"1,230:12,77,230:22,-1:4,230:3,-1:11,230:11,78,230:23,-1:4,230:3,-1:11,230:1" +
"9,79,230:15,-1:4,230:3,-1:11,230:11,80,230:23,-1:4,230:3,-1:11,230:11,81,23" +
"0:23,-1:4,230:3,-1:11,230:19,82,230:15,-1:4,230:3,-1:11,230:12,83,230:22,-1" +
":4,230:3,-1:11,230:19,84,230:15,-1:4,230:3,-1:11,230:6,85,230:28,-1:4,230:3" +
",-1:11,230:9,86,230:25,-1:4,230:3,-1:11,230:10,87,230:24,-1:4,230:3,-1:11,2" +
"30:10,88,230:24,-1:4,230:3,-1:11,230:10,89,230:24,-1:4,230:3,-1:11,230:19,9" +
"0,230:15,-1:4,230:3,-1:11,230:10,91,230:24,-1:4,230:3,-1:11,230:23,92,230:1" +
"1,-1:4,230:3,-1:11,230:19,93,230:15,-1:4,230:3,-1:11,230:8,94,230:26,-1:4,2" +
"30:3,-1:11,230:19,95,230:15,-1:4,230:3,-1:11,230:10,96,230:24,-1:4,230:3,-1" +
":11,230:8,97,230:26,-1:4,230:3,-1:11,230:8,98,230:26,-1:4,230:3,-1:11,230:1" +
"1,99,230:23,-1:4,230:3,-1:11,230:7,100,230:27,-1:4,230:3,-1:11,230:8,101,23" +
"0:26,-1:4,230:3,-1:11,230:11,102,230:23,-1:4,230:3,-1:11,230:6,103,230:28,-" +
"1:4,230:3,-1:11,230:8,104,230:26,-1:4,230:3,-1:11,230:29,105,230:5,-1:4,230" +
":3,-1:11,230:8,106,230:26,-1:4,230:3,-1:11,230:15,107,230:19,-1:4,230:3,-1:" +
"11,230:7,108,230:27,-1:4,230:3,-1:11,230:10,210,230:24,-1:4,230:3,-1:11,230" +
":15,128,230:19,-1:4,230:3,-1:11,230:9,129,230:25,-1:4,230:3,-1:11,230:6,211" +
",230:28,-1:4,230:3,-1:11,230:3,130,230:31,-1:4,230:3,-1:11,230:8,131,230:26" +
",-1:4,230:3,-1:11,230:12,132,230:22,-1:4,230:3,-1:11,230:16,133,230:18,-1:4" +
",230:3,-1:11,230:19,135,230:15,-1:4,230:3,-1:11,230:20,136,230:14,-1:4,230:" +
"3,-1:11,230:23,212,230:11,-1:4,230:3,-1:11,230:34,138,-1:4,230:3,-1:11,230:" +
"15,139,230:19,-1:4,230:3,-1:11,230:16,109,230:18,-1:4,230:3,-1:11,230:16,21" +
"3,230:18,-1:4,230:3,-1:11,230:8,140,230:26,-1:4,230:3,-1:11,230:11,141,230:" +
"23,-1:4,230:3,-1:11,230:19,214,230:15,-1:4,230:3,-1:11,230:6,143,230:28,-1:" +
"4,230:3,-1:11,230:20,144,230:14,-1:4,230:3,-1:11,230:21,146,230:13,-1:4,230" +
":3,-1:11,230:7,217,230:27,-1:4,230:3,-1:11,230:14,236,230:20,-1:4,230:3,-1:" +
"11,230:12,148,230:22,-1:4,230:3,-1:11,230:11,218,230:23,-1:4,230:3,-1:11,23" +
"0:10,219,230:24,-1:4,230:3,-1:11,230:22,149,230:12,-1:4,230:3,-1:11,230:15," +
"152,230:19,-1:4,230:3,-1:11,230:28,153,230:6,-1:4,230:3,-1:11,230:12,155,23" +
"0:22,-1:4,230:3,-1:11,230:10,156,230:24,-1:4,230:3,-1:11,230:7,157,230:27,-" +
"1:4,230:3,-1:11,230:16,158,230:18,-1:4,230:3,-1:11,230:11,159,230:23,-1:4,2" +
"30:3,-1:11,230:27,160,230:7,-1:4,230:3,-1:11,230:21,238,230:13,-1:4,230:3,-" +
"1:11,230:26,162,230:8,-1:4,230:3,-1:11,230:8,163,230:26,-1:4,230:3,-1:11,23" +
"0:9,165,230:25,-1:4,230:3,-1:11,230:12,166,230:22,-1:4,230:3,-1:11,230:11,1" +
"67,230:23,-1:4,230:3,-1:11,230:17,168,230:17,-1:4,230:3,-1:11,230:27,169,23" +
"0:7,-1:4,230:3,-1:11,230:23,170,230:11,-1:4,230:3,-1:11,230:6,223,230:28,-1" +
":4,230:3,-1:11,230:14,229,230:20,-1:4,230:3,-1:11,230:13,171,230:21,-1:4,23" +
"0:3,-1:11,230:7,172,230:27,-1:4,230:3,-1:11,230:10,173,230:24,-1:4,230:3,-1" +
":11,230:8,175,230:26,-1:4,230:3,-1:11,230:17,176,230:17,-1:4,230:3,-1:11,17" +
"9,230:34,-1:4,230:3,-1:11,230:31,110,230:3,-1:4,230:3,-1:11,230:6,224,230:2" +
"8,-1:4,230:3,-1:11,230:24,180,230:10,-1:4,230:3,-1:11,230:7,181,230:27,-1:4" +
",230:3,-1:11,230:10,182,230:24,-1:4,230:3,-1:11,230:15,183,230:19,-1:4,230:" +
"3,-1:11,230:8,184,230:26,-1:4,230:3,-1:11,230:14,185,230:20,-1:4,230:3,-1:1" +
"1,230:23,225,230:11,-1:4,230:3,-1:11,230:28,187,230:6,-1:4,230:3,-1:11,230:" +
"6,188,230:28,-1:4,230:3,-1:11,230:12,189,230:22,-1:4,230:3,-1:11,230:21,190" +
",230:13,-1:4,230:3,-1:11,230:12,111,230:22,-1:4,230:3,-1:11,230:8,191,230:2" +
"6,-1:4,230:3,-1:11,230:19,193,230:15,-1:4,230:3,-1:11,230:10,194,230:24,-1:" +
"4,230:3,-1:11,230:17,195,230:17,-1:4,230:3,-1:11,230,226,230:33,-1:4,230:3," +
"-1:11,230:18,196,230:16,-1:4,230:3,-1:11,230:12,197,230:22,-1:4,230:3,-1:11" +
",230:22,198,230:12,-1:4,230:3,-1:11,230:8,199,230:26,-1:4,230:3,-1:11,230:1" +
"0,200,230:24,-1:4,230:3,-1:11,230:14,112,230:20,-1:4,230:3,-1:11,230:19,113" +
",230:15,-1:4,230:3,-1:11,230:12,202,230:22,-1:4,230:3,-1:11,230:18,203,230:" +
"16,-1:4,230:3,-1:11,230:6,227,230:28,-1:4,230:3,-1:11,230:32,114,230:2,-1:4" +
",230:3,-1:11,230:10,204,230:24,-1:4,230:3,-1:11,230:14,115,230:20,-1:4,230:" +
"3,-1:11,230:11,206,230:23,-1:4,230:3,-1:11,230:8,207,230:26,-1:4,230:3,-1:1" +
"1,230:20,116,230:14,-1:4,230:3,-1:11,230:18,208,230:16,-1:4,230:3,-1:11,230" +
":14,117,230:20,-1:4,230:3,-1:11,230:20,121,230:14,-1:4,230:3,-1:11,230:15,1" +
"34,230:19,-1:4,230:3,-1:11,230:12,137,230:22,-1:4,230:3,-1:11,230:8,215,230" +
":26,-1:4,230:3,-1:11,230:6,145,230:28,-1:4,230:3,-1:11,230:21,216,230:13,-1" +
":4,230:3,-1:11,230:7,147,230:27,-1:4,230:3,-1:11,230:14,151,230:20,-1:4,230" +
":3,-1:11,230:11,150,230:23,-1:4,230:3,-1:11,230:10,154,230:24,-1:4,230:3,-1" +
":11,230:15,220,230:19,-1:4,230:3,-1:11,230:12,161,230:22,-1:4,230:3,-1:11,2" +
"30:16,164,230:18,-1:4,230:3,-1:11,230:23,174,230:11,-1:4,230:3,-1:11,230:10" +
",177,230:24,-1:4,230:3,-1:11,230:10,186,230:24,-1:4,230:3,-1:11,230:6,192,2" +
"30:28,-1:4,230:3,-1:11,230:12,201,230:22,-1:4,230:3,-1:11,230:10,205,230:24" +
",-1:4,230:3,-1:11,230:25,122,230:9,-1:4,230:3,-1:11,230:10,178,230:24,-1:4," +
"230:3,-1:11,230:23,123,230:11,-1:4,230:3,-1:11,230:15,124,230:19,-1:4,230:3" +
",-1:11,230:19,125,230:15,-1:4,230:3,-1:11,230:15,126,230:19,-1:4,230:3,-1:1" +
"1,230:33,127,230,-1:4,230:3,-1:11,230:10,237,230:24,-1:4,230:3,-1:11,230:15" +
",221,230:19,-1:4,230:3,-1:11,230:8,222,230:26,-1:4,230:3,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {
				return null;
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return new Symbol(sym._SYMB_0); }
					case -3:
						break;
					case 3:
						{ return new Symbol(sym._SYMB_1); }
					case -4:
						break;
					case 4:
						{ return new Symbol(sym._SYMB_2); }
					case -5:
						break;
					case 5:
						{ return new Symbol(sym._SYMB_3); }
					case -6:
						break;
					case 6:
						{ return new Symbol(sym._SYMB_5); }
					case -7:
						break;
					case 7:
						{ return new Symbol(sym._SYMB_7); }
					case -8:
						break;
					case 8:
						{ return new Symbol(sym._SYMB_8); }
					case -9:
						break;
					case 9:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -10:
						break;
					case 10:
						{ return new Symbol(sym._INTEGER_, new Integer(yytext())); }
					case -11:
						break;
					case 11:
						{ /* ignore white space. */ }
					case -12:
						break;
					case 12:
						{ return new Symbol(sym._SYMB_4); }
					case -13:
						break;
					case 13:
						{ yybegin(COMMENT); }
					case -14:
						break;
					case 14:
						{ return new Symbol(sym._SYMB_6); }
					case -15:
						break;
					case 15:
						{ return new Symbol(sym._SYMB_9); }
					case -16:
						break;
					case 16:
						{ return new Symbol(sym._SYMB_10); }
					case -17:
						break;
					case 17:
						{ return new Symbol(sym._SYMB_11); }
					case -18:
						break;
					case 18:
						{ /* BNFC single-line comment */ }
					case -19:
						break;
					case 19:
						{ yybegin(COMMENT); }
					case -20:
						break;
					case 20:
						{ return new Symbol(sym._SYMB_16); }
					case -21:
						break;
					case 21:
						{ return new Symbol(sym._SYMB_18); }
					case -22:
						break;
					case 22:
						{ return new Symbol(sym._SYMB_21); }
					case -23:
						break;
					case 23:
						{ return new Symbol(sym._SYMB_12); }
					case -24:
						break;
					case 24:
						{ return new Symbol(sym._SYMB_22); }
					case -25:
						break;
					case 25:
						{ return new Symbol(sym._SYMB_19); }
					case -26:
						break;
					case 26:
						{ return new Symbol(sym._SYMB_24); }
					case -27:
						break;
					case 27:
						{ return new Symbol(sym._SYMB_13); }
					case -28:
						break;
					case 28:
						{ return new Symbol(sym._SYMB_14); }
					case -29:
						break;
					case 29:
						{ return new Symbol(sym._SYMB_20); }
					case -30:
						break;
					case 30:
						{ return new Symbol(sym._SYMB_23); }
					case -31:
						break;
					case 31:
						{ return new Symbol(sym._SYMB_15); }
					case -32:
						break;
					case 32:
						{ return new Symbol(sym._SYMB_17); }
					case -33:
						break;
					case 33:
						{ }
					case -34:
						break;
					case 34:
						{ }
					case -35:
						break;
					case 35:
						{ yybegin(YYINITIAL); }
					case -36:
						break;
					case 36:
						{ yybegin(YYINITIAL); }
					case -37:
						break;
					case 38:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -38:
						break;
					case 39:
						{ }
					case -39:
						break;
					case 41:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -40:
						break;
					case 43:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -41:
						break;
					case 45:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -42:
						break;
					case 47:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -43:
						break;
					case 49:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -44:
						break;
					case 50:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -45:
						break;
					case 51:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -46:
						break;
					case 52:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -47:
						break;
					case 53:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -48:
						break;
					case 54:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -49:
						break;
					case 55:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -50:
						break;
					case 56:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -51:
						break;
					case 57:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -52:
						break;
					case 58:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -53:
						break;
					case 59:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -54:
						break;
					case 60:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -55:
						break;
					case 61:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -56:
						break;
					case 62:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -57:
						break;
					case 63:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -58:
						break;
					case 64:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -59:
						break;
					case 65:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -60:
						break;
					case 66:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -61:
						break;
					case 67:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -62:
						break;
					case 68:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -63:
						break;
					case 69:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -64:
						break;
					case 70:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -65:
						break;
					case 71:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -66:
						break;
					case 72:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -67:
						break;
					case 73:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -68:
						break;
					case 74:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -69:
						break;
					case 75:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -70:
						break;
					case 76:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -71:
						break;
					case 77:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -72:
						break;
					case 78:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -73:
						break;
					case 79:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -74:
						break;
					case 80:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -75:
						break;
					case 81:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -76:
						break;
					case 82:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -77:
						break;
					case 83:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -78:
						break;
					case 84:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -79:
						break;
					case 85:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -80:
						break;
					case 86:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -81:
						break;
					case 87:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -82:
						break;
					case 88:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -83:
						break;
					case 89:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -84:
						break;
					case 90:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -85:
						break;
					case 91:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -86:
						break;
					case 92:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -87:
						break;
					case 93:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -88:
						break;
					case 94:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -89:
						break;
					case 95:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -90:
						break;
					case 96:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -91:
						break;
					case 97:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -92:
						break;
					case 98:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -93:
						break;
					case 99:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -94:
						break;
					case 100:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -95:
						break;
					case 101:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -96:
						break;
					case 102:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -97:
						break;
					case 103:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -98:
						break;
					case 104:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -99:
						break;
					case 105:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -100:
						break;
					case 106:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -101:
						break;
					case 107:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -102:
						break;
					case 108:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -103:
						break;
					case 109:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -104:
						break;
					case 110:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -105:
						break;
					case 111:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -106:
						break;
					case 112:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -107:
						break;
					case 113:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -108:
						break;
					case 114:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -109:
						break;
					case 115:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -110:
						break;
					case 116:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -111:
						break;
					case 117:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -112:
						break;
					case 118:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -113:
						break;
					case 119:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -114:
						break;
					case 120:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -115:
						break;
					case 121:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -116:
						break;
					case 122:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -117:
						break;
					case 123:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -118:
						break;
					case 124:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -119:
						break;
					case 125:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -120:
						break;
					case 126:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -121:
						break;
					case 127:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -122:
						break;
					case 128:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -123:
						break;
					case 129:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -124:
						break;
					case 130:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -125:
						break;
					case 131:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -126:
						break;
					case 132:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -127:
						break;
					case 133:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -128:
						break;
					case 134:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -129:
						break;
					case 135:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -130:
						break;
					case 136:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -131:
						break;
					case 137:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -132:
						break;
					case 138:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -133:
						break;
					case 139:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -134:
						break;
					case 140:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -135:
						break;
					case 141:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -136:
						break;
					case 142:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -137:
						break;
					case 143:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -138:
						break;
					case 144:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -139:
						break;
					case 145:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -140:
						break;
					case 146:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -141:
						break;
					case 147:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -142:
						break;
					case 148:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -143:
						break;
					case 149:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -144:
						break;
					case 150:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -145:
						break;
					case 151:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -146:
						break;
					case 152:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -147:
						break;
					case 153:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -148:
						break;
					case 154:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -149:
						break;
					case 155:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -150:
						break;
					case 156:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -151:
						break;
					case 157:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -152:
						break;
					case 158:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -153:
						break;
					case 159:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -154:
						break;
					case 160:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -155:
						break;
					case 161:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -156:
						break;
					case 162:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -157:
						break;
					case 163:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -158:
						break;
					case 164:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -159:
						break;
					case 165:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -160:
						break;
					case 166:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -161:
						break;
					case 167:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -162:
						break;
					case 168:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -163:
						break;
					case 169:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -164:
						break;
					case 170:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -165:
						break;
					case 171:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -166:
						break;
					case 172:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -167:
						break;
					case 173:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -168:
						break;
					case 174:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -169:
						break;
					case 175:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -170:
						break;
					case 176:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -171:
						break;
					case 177:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -172:
						break;
					case 178:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -173:
						break;
					case 179:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -174:
						break;
					case 180:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -175:
						break;
					case 181:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -176:
						break;
					case 182:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -177:
						break;
					case 183:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -178:
						break;
					case 184:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -179:
						break;
					case 185:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -180:
						break;
					case 186:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -181:
						break;
					case 187:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -182:
						break;
					case 188:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -183:
						break;
					case 189:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -184:
						break;
					case 190:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -185:
						break;
					case 191:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -186:
						break;
					case 192:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -187:
						break;
					case 193:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -188:
						break;
					case 194:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -189:
						break;
					case 195:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -190:
						break;
					case 196:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -191:
						break;
					case 197:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -192:
						break;
					case 198:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -193:
						break;
					case 199:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -194:
						break;
					case 200:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -195:
						break;
					case 201:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -196:
						break;
					case 202:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -197:
						break;
					case 203:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -198:
						break;
					case 204:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -199:
						break;
					case 205:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -200:
						break;
					case 206:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -201:
						break;
					case 207:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -202:
						break;
					case 208:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -203:
						break;
					case 209:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -204:
						break;
					case 210:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -205:
						break;
					case 211:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -206:
						break;
					case 212:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -207:
						break;
					case 213:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -208:
						break;
					case 214:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -209:
						break;
					case 215:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -210:
						break;
					case 216:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -211:
						break;
					case 217:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -212:
						break;
					case 218:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -213:
						break;
					case 219:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -214:
						break;
					case 220:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -215:
						break;
					case 221:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -216:
						break;
					case 222:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -217:
						break;
					case 223:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -218:
						break;
					case 224:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -219:
						break;
					case 225:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -220:
						break;
					case 226:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -221:
						break;
					case 227:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -222:
						break;
					case 228:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -223:
						break;
					case 229:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -224:
						break;
					case 230:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -225:
						break;
					case 231:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -226:
						break;
					case 232:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -227:
						break;
					case 233:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -228:
						break;
					case 234:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -229:
						break;
					case 235:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -230:
						break;
					case 236:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -231:
						break;
					case 237:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -232:
						break;
					case 238:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -233:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
