#!/bin/sh

# Check the number of command-line arguments
if [ \( "$#" -eq 0 \) ] ; then
	echo "usage: ${0} <file> [params]"
	exit 1
fi

if [ $(uname) = "Linux" ]; then
    pathCmd="readlink -f"
elif [ $(uname) = "Darwin" ]; then
    pathCmd="stat -f %N"
else
    pathCmd="realpath"
fi
SRC="${1}"

LIVENESSBASE="`dirname $($pathCmd $0)`/../LivenessProver/"

# set the base directory
BASEDIR="${LIVENESSBASE}"

# run the main script
. ../LivenessProver/autosat

cp ${SRC} "${OUTPUT_DIR}/source.txt"
cd ${OUTPUT_DIR} && ./alltosvg
