#!/bin/bash

# Check the number of command-line arguments
if [ \( "$#" -eq 0 \) ] ; then
	echo "usage: ${0} <file> [params]"
	exit 1
fi

# source file
FILE=$1
# get rid of the first argument
shift


# name of the file with encoded enabledness
ENABLED_ENC_FILE=`mktemp /tmp/fair.XXXXXXXXXXX`
# name of the file with encoded fairness
FAIR_ENC_FILE=`mktemp /tmp/fair.XXXXXXXXXXX`


# enabledness encoder
ENABLED_ENCODER="fair/enabled_encode.py"
# fairness encoder
FAIR_ENCODER="fair/fair_encode.py"


OUTPUT_DIR="./output"

cd ${OUTPUT_DIR} && ./clean_dir && cd ..

# encode enablednes
${ENABLED_ENCODER} ${FILE} > ${ENABLED_ENC_FILE}
rc=$?
if [[ $rc != 0 ]]; then
	echo "Error when encoding enabledness into the model"
	exit $rc
fi

# encode fairness
${FAIR_ENCODER} ${ENABLED_ENC_FILE} > ${FAIR_ENC_FILE}
rc=$?
if [[ $rc != 0 ]]; then
	echo "Error when encoding fairness into the model"
	exit $rc
fi

# copy the outputs of the scripts
cp ${FILE} "${OUTPUT_DIR}/source.txt"
cp ${ENABLED_ENC_FILE} "${OUTPUT_DIR}/enabled_encoded.txt"
cp ${FAIR_ENC_FILE} "${OUTPUT_DIR}/fair_encoded.txt"

# run the usual stuff
./runFancy ${FAIR_ENC_FILE} $@ | tee ${OUTPUT_DIR}/output.log
