#!/bin/sh

# Check the number of command-line arguments
if [ \( "$#" -eq 0 \) ] ; then
	echo "usage: ${0} <file> [params]"
	exit 1
fi

if [ $(uname) = "Linux" ]; then
    pathCmd="readlink -f"
elif [ $(uname) = "Darwin" ]; then
    pathCmd="stat -f %N"
else
    pathCmd="realpath"
fi
SRC="${1}"

OUTPUT_DIR="./output"

LIVENESSBASE="`dirname $($pathCmd $0)`/../LivenessProver/"

# set the base directory for the main script
export BASEDIR="${LIVENESSBASE}"

# run in case the core verifier will not terminate
cd ${OUTPUT_DIR} && ./alltosvg && cd ..

# run the main script
. ../LivenessProver/slrp

cp ${SRC} "${OUTPUT_DIR}/slrp_input.txt"
cd ${OUTPUT_DIR} && ./alltosvg && cd ..
