package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class AcceptingRule implements java.io.Serializable {
  public abstract <R,A> R accept(AcceptingRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.TransducerAccepting p, A arg);

  }

}
