package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class AutomataAcceptingsRule implements java.io.Serializable {
  public abstract <R,A> R accept(AutomataAcceptingsRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.AutomataAcceptings p, A arg);

  }

}
