package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class InitStateAutomatonRule implements java.io.Serializable {
  public abstract <R,A> R accept(InitStateAutomatonRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.NumOfInitStatesAutomatonGuess p, A arg);
    public R visit(grammar.Absyn.NoInitStatesAutomatonGuess p, A arg);

  }

}
