package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class MaybeClosed implements java.io.Serializable {
  public abstract <R,A> R accept(MaybeClosed.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.ClosedInit p, A arg);
    public R visit(grammar.Absyn.NotClosedInit p, A arg);

  }

}
