package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class StateTransducerRule implements java.io.Serializable {
  public abstract <R,A> R accept(StateTransducerRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.NumOfStatesTransducerGuess p, A arg);

  }

}
