package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class StateAutomatonRule implements java.io.Serializable {
  public abstract <R,A> R accept(StateAutomatonRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.NumOfStatesAutomatonGuess p, A arg);

  }

}
