#!/bin/sh

exec java -Xss20000k -Xmx2000m -cp dist/symmetryencoding.jar:../Common/lib/commons-io-2.4.jar:../Common/lib/commons-cli-1.2.jar:../Common/lib/org.sat4j.core.jar:../Common/lib/log4j-core-2.1.jar:../Common/lib/log4j-api-2.1.jar:../Common/lib/java-cup-11a.jar symmetryencoding.Main "$@"
