package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ImpossiblePairs extends Statement {
  public final ListImpossiblePairRule listimpossiblepairrule_;
  public ImpossiblePairs(ListImpossiblePairRule p1) { listimpossiblepairrule_ = p1; }

  public <R,A> R accept(grammar.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ImpossiblePairs) {
      grammar.Absyn.ImpossiblePairs x = (grammar.Absyn.ImpossiblePairs)o;
      return this.listimpossiblepairrule_.equals(x.listimpossiblepairrule_);
    }
    return false;
  }

  public int hashCode() {
    return this.listimpossiblepairrule_.hashCode();
  }


}
