package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class ImpossiblePairRule implements java.io.Serializable {
  public abstract <R,A> R accept(ImpossiblePairRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.ImpossiblePair p, A arg);

  }

}
