package grammar.Absyn; // Java Package generated by the BNF Converter.

public class LiteralName extends Name {
  public final String ident_;
  public LiteralName(String p1) { ident_ = p1; }

  public <R,A> R accept(grammar.Absyn.Name.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.LiteralName) {
      grammar.Absyn.LiteralName x = (grammar.Absyn.LiteralName)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
