package grammar.Absyn; // Java Package generated by the BNF Converter.

public class Model extends ModelRule {
  public final TransducerRule transducerrule_;
  public final ListStatement liststatement_;
  public Model(TransducerRule p1, ListStatement p2) { transducerrule_ = p1; liststatement_ = p2; }

  public <R,A> R accept(grammar.Absyn.ModelRule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.Model) {
      grammar.Absyn.Model x = (grammar.Absyn.Model)o;
      return this.transducerrule_.equals(x.transducerrule_) && this.liststatement_.equals(x.liststatement_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.transducerrule_.hashCode())+this.liststatement_.hashCode();
  }


}
