package grammar.Absyn; // Java Package generated by the BNF Converter.

public class NameSequence extends NameSequenceRule {
  public final ListNameSpaceRule listnamespacerule_;
  public NameSequence(ListNameSpaceRule p1) { listnamespacerule_ = p1; }

  public <R,A> R accept(grammar.Absyn.NameSequenceRule.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.NameSequence) {
      grammar.Absyn.NameSequence x = (grammar.Absyn.NameSequence)o;
      return this.listnamespacerule_.equals(x.listnamespacerule_);
    }
    return false;
  }

  public int hashCode() {
    return this.listnamespacerule_.hashCode();
  }


}
