package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class TransitionRule implements java.io.Serializable {
  public abstract <R,A> R accept(TransitionRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.FulTransition p, A arg);
    public R visit(grammar.Absyn.EmptyTransition p, A arg);
    public R visit(grammar.Absyn.LoopingTransition p, A arg);

  }

}
