package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class TransducerRule implements java.io.Serializable {
  public abstract <R,A> R accept(TransducerRule.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.Transducer p, A arg);

  }

}
