package grammar.Absyn; // Java Package generated by the BNF Converter.

public class TurnOffConditions extends Statement {
  public final ListCheckingConditionRule listcheckingconditionrule_;
  public TurnOffConditions(ListCheckingConditionRule p1) { listcheckingconditionrule_ = p1; }

  public <R,A> R accept(grammar.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.TurnOffConditions) {
      grammar.Absyn.TurnOffConditions x = (grammar.Absyn.TurnOffConditions)o;
      return this.listcheckingconditionrule_.equals(x.listcheckingconditionrule_);
    }
    return false;
  }

  public int hashCode() {
    return this.listcheckingconditionrule_.hashCode();
  }


}
